version: '3.7'
services:
  frontend:
    image: public.ecr.aws/x2b9z2t7/storedog/frontend:1.0.1
    command: yarn dev
    volumes:
      - "../../services/frontend/site:/storedog-app/site"
    ports:
      - 3000:3000
    networks:
      - storedog-backend_storedog-net
  nginx:
    image: public.ecr.aws/x2b9z2t7/storedog/nginx:1.0.1
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
    labels:
      com.datadoghq.ad.logs: '[{"source": "nginx", "service": "nginx"}]'
    networks:
      - storedog-backend_storedog-net

networks:
  storedog-backend_storedog-net:
    external: true
